# Generated by Django 5.1.7 on 2025-03-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
