# Generated by Django 4.2.11 on 2025-03-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deposited', 'Deposit Received'), ('released', 'Payment Released'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bid',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
